<a href="https://colab.research.google.com/github/CrestwoodCustomSolutions/Crestwood-PythonClass/blob/main/Level_11_Part_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# Lesson 11.4
import pandas as pd
import polars as pl

# Read external data / files
# Polar
pl_csv_loaded = pl.read_csv("/content/sample_data/california_housing_test.csv")
pl_csv_loaded.head(5)  # 5 rows
pl_csv_loaded.tail(5)  # 5 rows

shape: (5, 9)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ longitude ┆ latitude ┆ housing_m ┆ total_roo ┆ … ┆ populatio ┆ household ┆ median_in ┆ median_ho │
│ ---       ┆ ---      ┆ edian_age ┆ ms        ┆   ┆ n         ┆ s         ┆ come      ┆ use_value │
│ f64       ┆ f64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆          ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ -119.86   ┆ 34.42    ┆ 23.0      ┆ 1450.0    ┆ … ┆ 1258.0    ┆ 607.0     ┆ 1.179     ┆ 225000.0  │
│ -118.14   ┆ 34.06    ┆ 27.0      ┆ 5257.0    ┆ … ┆ 3496.0    ┆ 1036.0    ┆ 3.3906    ┆ 237200.0  │
│ -119.7    ┆ 36.3     ┆ 10.0      ┆ 956.0     ┆ … ┆ 693.0     ┆ 220.0     ┆ 2.2895    ┆ 62000.0   │
│ -117.12   ┆ 34.1     ┆ 40.0      ┆ 96.0      ┆ … ┆ 46.0      ┆ 14.0      ┆ 3.2708    ┆ 162500.0  │
│ -119.63   ┆ 34.42    ┆ 42.0      ┆ 1765.0    ┆ … ┆ 753.0     ┆ 260.0     ┆ 8.5608    ┆ 500001.0  │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
# Panda
pd_csv_loaded = pd.read_csv("/content/sample_data/california_housing_test.csv")
pd_csv_loaded.head(5)  # 5 rows
pd_csv_loaded.tail(5)  # 5 rows

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [9]:
pd_csv_loaded.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

In [13]:
pd_csv_loaded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

In [17]:
pd_csv_loaded.loc["longitude"]
pd_csv_loaded.iloc[3]

longitude               -118.3600
latitude                  33.8200
housing_median_age        28.0000
total_rooms               67.0000
total_bedrooms            15.0000
population                49.0000
households                11.0000
median_income              6.1359
median_house_value    330000.0000
Name: 3, dtype: float64

In [22]:
# Polar
pl_csv_loaded.describe()
pl_csv_loaded.schema
pl_csv_loaded.shape

(3000, 9)